[package]
name = "rs64"
version = "0.1.0"
authors = ["toast"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.13.0"
colorful = "0.2.1"
rand = "0.8.2"
